name: go-service-template

services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: db-postgres
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  postgres-migrate:
    image: ghcr.io/kukymbr/goose-docker:3.22.1
    container_name: pg-migrate
    restart: on-failure:2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=${DB_HOST} port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME}
    volumes:
      - ./migrations/postgres:/migrations

  wizards-rest:
    build: .
    container_name: wizards-rest-service
    restart: unless-stopped
    command: ["/wizards-rest"]
    env_file: .env
    ports:
      - ${APP_WIZARDS_REST_PORT}:5050
    depends_on:
      postgres:
        condition: service_healthy
      postgres-migrate:
        condition: service_completed_successfully

volumes:
  pgdata:
    name: pgdata
