version: '3.9'

name: go-service-template

services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: db-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  plain-http:
    build: .
    container_name: plain-http-service
    restart: unless-stopped
    command: ["/plain-http"]
    ports:
      - ${APP_PLAIN_HTTP_PORT}:5050
    depends_on:
      postgres:
        condition: service_healthy
